#!/usr/bin/env node

const { createConnection } = require('net');

const ipcClient = createConnection('/tmp/tau-morrow');

const key = process.argv[2];

ipcClient.on('data', data => {
  const str = data.toString('utf-8');
  const obj = JSON.parse(str);
  const value = obj[key];
  switch (typeof value) {
    case 'number':
      console.log(value.toFixed(2));
      break;
    default:
      console.log(value);
      break;
  }
});
